### PR TITLE
UI Tweaks for StudentView

### LINKED ISSUE #278: Info section of student view collapses when intervention or outreach section's heights are large.

### PR DESCRIPTION
**Pull request by dting**
Resolves #278.

- Removes some extra margins for interventions and outreaches.
- Rework some outreach menu behavior and styles.
- Add animation to dropdown toggle.

@pdotsani

### CODE REVIEW

**Comment by pdotsani** [comment]
@dting is there a way I can preview these changes by cloning your branch into my local machine, or is this branch exclusively accessible to you alone?

**Comment by dting** [comment]
You can add my repository as a remote in git and fetch the changes then check them out.

**Comment by dting** [comment]
Another way to do it is: 

https://help.github.com/articles/checking-out-pull-requests-locally/

**Comment by dting** [comment]
git checkout -b dting-StudentViewUITweaks master
git pull https://github.com/dting/webapp.git StudentViewUITweaks

**Comment by pdotsani** [comment]
lgtm.

**Pull request merged**
