### PR TITLE
enable student data export, pdf export, select export

### PR DESCRIPTION
**Pull request by pdotsani**
resolves #183 

@dting 

enabled student data export
enabled select admin data export
installed bower package pdfmake

run bower install or bower install pdfmake --save

### CODE REVIEW

**Comment by dting** [comment]
lgtm

**Comment by dting** [comment]
Let's follow this up with a change list that cleans up the exported data. Do you want to work on that?

**Comment by pdotsani** [comment]
@dting sure

**Comment by pdotsani** [comment]
@dting 
Added changelists as we discussed, let me know what you think.

**Comment by dting** [comment]
This LGTM.

**Pull request merged**
